// This file is automatically generated by ABP framework to use MVC Controllers from CSharp
using MasterAbp.Products;
using System;
using System.Collections.Generic;
using Volo.Abp;
using Volo.Abp.Application.Dtos;
using Volo.Abp.ObjectExtending;

// ReSharper disable once CheckNamespace
namespace MasterAbp.Products;

public class CreateUpdateProductDto
{
    public Guid CategoryId { get; set; }

    public string Name { get; set; }

    public Single Price { get; set; }

    public bool IsFreeCargo { get; set; }

    public DateTime ReleaseDate { get; set; }

    public ProductStockState StockState { get; set; }
}
