// This file is automatically generated by ABP framework to use MVC Controllers from CSharp
using MasterAbp.Products;
using System;
using System.Collections.Generic;
using Volo.Abp;
using Volo.Abp.Application.Dtos;
using Volo.Abp.ObjectExtending;

// ReSharper disable once CheckNamespace
namespace MasterAbp.Products;

public enum ProductStockState
{
    PreOrder = 0,
    InStock = 1,
    NotAvailable = 2,
    Stopped = 3
}
