// This file is automatically generated by ABP framework to use MVC Controllers from CSharp
using MasterAbp.Products;
using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Volo.Abp;
using Volo.Abp.Application.Dtos;
using Volo.Abp.Application.Services;

// ReSharper disable once CheckNamespace
namespace MasterAbp.Controllers.Products;

public interface IProductAppService : IApplicationService
{
    Task<PagedResultDto<ProductDto>> GetListAsync(PagedAndSortedResultRequestDto input);

    Task<ProductDto> CreateAsync(CreateUpdateProductDto input);

    Task<ListResultDto<CategoryLookupDto>> GetCategoriesAsync();

    Task<ProductDto> GetAsync(Guid id);

    Task UpdateAsync(Guid id, CreateUpdateProductDto input);

    Task DeleteAsync(Guid id);
}
